### ISSUE TITLE
Export images in uber quality

### ISSUE THREAD

**Issue by adrielcafe** [pramberg451/gwentCardExporter#1]
First of all, thanks for start this awesome project! I'm developing a wallpaper app and this will help me a lot .

It's possible to add an option to choose the image quality? I would like to export in uber quality.

Or you can add instructions of how to build the project manually, so I can made the changes to fit my needs.

**Comment by pramberg451** [comment]
Hello!

Choosing a quality option was actually on the original list of things I wanted but I discarded it for now because I realized I would have to redo all of my assets. Its something I want to do but would just take a lot of time. I need to take another look at the way I manage assets anyways because the numbers can't go past whatever the largest number is in the game at the moment which means they would be inaccurate if say a card ever reached 16 or 17 strength.

For a quick way to get uber quality images you can use this: https://github.com/Perfare/AssetStudio/releases
Once you have it installed simply "Load folder" and navigate to the uber folder found at 
..\Gwent_Data\StreamingAssets\bundledassets\cardassets\textures\standard\uber
Its a great way to browse all the assets in the game if you need more than just card images for your app.

As for building the project manually I will have more detailed instructions up soon but for now simply cloning the repository and making sure you have all the imports found in gwentCardImageExporter.py and GwentUtils.py installed should do the trick.
Here are the third-party ones.
https://pypi.org/project/pygubu/
https://pypi.org/project/UnityPy/
https://pypi.org/project/texture2ddecoder/
It was made and tested on Python 3.8.2.
I am fairly new to python myself but if you have any issues let me know!
If you also have any general issues please let me know I haven't had anyone else to test.
Cheers

**Comment by pramberg451** [comment]
If you also have any general issues please let me know I haven't had anyone else to test.

**Comment by adrielcafe** [comment]
Thanks for the tip, AssetStudio did the job, even exported the cardbacks.

I had no issue when exporting through your project, it ran very smoothly.

I'll keep following for future updates, this is very promissing!
