### ISSUE TITLE
Since last update of Gwent card exporting is stuck

### ISSUE THREAD

**Issue by VasaXter** [pramberg451/gwentCardExporter#3]
Since last updates (or more the last pack of updates) the Gwent card explorer stuck in generating the cards.
Everything works, it loads the cards but generate stuck at start. Cancel does anything. 
The first 7 items are there since I use it, in reality the 8 item is first generated card, so stucking at 7 means it stopped before first really generated card.
Tried multiple things on my side, same result.
![obrazek](https://user-images.githubusercontent.com/80281885/206701745-cdd4e30c-f8a6-4a47-81e3-7e575a7ced98.png)

Thank you for looking into this, as for fan of Witcher world this is important tool for me (I wish it could generate also the animated cards and cardbacks, that would be awesome).

**Comment by VasaXter** [comment]
Tested on different setup, fresh install of Gwent, Card Explorer, result was the same

**Comment by pramberg451** [comment]
> Tested on different setup, fresh install of Gwent, Card Explorer, result was the same

Hello! From what I can tell the error seems to come from a change that was made to how the unity files are formatted for the game which is something I have very little control over in my code since it's handled by library functions. I'll see if I can get in touch with the UnityPy dev and see if they can figure anything out. It's difficult to figure out what changed without being able to compare it to an older installation of Gwent. It might take a while for me to get around to fixing it but I hope to have a version that works once CDPR has a final version of the game before they stop development work on it next year.

In the mean time [AssetStudio](https://github.com/Perfare/AssetStudio/releases) also works really well to get images in bulk (and also the cardbacks that you mentioned) you just have to do more digging through files. gwent.one is also a useful site.

Thanks!

**Comment by VasaXter** [comment]
> 

Hi. Thanks for the information. I hoped it will be just some unexpected occurrence during accessing the files, ready for quick fix. So I have high hopes you will succeed even if it turned other way around.
I do know gwent.one, that one is unsatisfying (in means of graphic data), but AssetStudio looks promising, at least for a while, even if it spams me with loading errors and looking for something is like mining gold from river :-D.

Thank you a lot!

**Comment by marie-altieri** [comment]
Hey there ! Any chance you have an update concerning this issue ? Asset Studio is a headache compared to this program. Cheers

**Comment by teddybee-r** [comment]
Hey

I'm bad at python (never coded a thing in this language - but I am maintaining a script for gwent.one (GwentCommunityDevelopers/gwent-data)) but after 2h of testing around I seem to have fixed it.

Since I am on Linux I had to modify a few things before I got things running (Case Sensitive File Names / no .ico support).
I did one run on low with borders, strength, provisions and it ran fine.

I also added some unreleased card sets to not break on the next set release.

This was tested with  UnityPy 1.9.26 - as of now current release

Cheers teddy

Edit: I seem to have left in the bigger window size since I had no generate button on Linux, sorry about that.

**Comment by pramberg451** [comment]
Thanks for looking into this! Pushed some changes after testing stuff out myself. Biggest thing was updating UnityPy and changing that code like you had it. I'll work on getting an executable release done sometime soon as it seems buggy at the moment. Let me know if you need any more small changes for Linux compatability as well.

**Comment by teddybee-r** [comment]
I had issues with assets/favicon.ico and google says tkinter doesnt support ico on linux so I just commented them out. Plus the window was too small so I made it bigger to have a Generate button.

The other issues were related to case sensitivity. For Windows armor.png and Armor.png are the same file while that is not the case in Linux.

**Comment by MoritzMusel** [comment]
Hi, is there any updates regarding unity file formatting? The newest version of Gwent (Steam, Windows) doesnt work for the exporter.

Cheers

**Comment by teddybee-r** [comment]
The exporter works if you run it from the command line with python. The standalone release was not updated yet.

**Comment by pramberg451** [comment]
> The exporter works if you run it from the command line with python. The standalone release was not updated yet.

Wanted to update you on this even though I haven't found a solution yet. Currently, updating UnityPy to fix this bug causes another bug where the executable is missing some file that UnityPy needs. I'm fairly certain it's an issue with UnityPy and not with pyinstaller which is used to create the executable. I've been unable to find a version of UnityPy that both fixes this issue and doesn't cause the new one. If I ever find a solution I'll post here but right now I'm too busy to go digging further for a solution. If anyone else wants to try using pyinstaller to create the executable from the normal python files and you get it to work, let me know and I'll update the release.

**Comment by pramberg451** [comment]
Fix was released in 1.4.0. 
https://github.com/pramberg451/gwentCardExporter/releases/tag/v1.4.0

This is the fix to the issue described in the comment above this one.
https://github.com/K0lb3/UnityPy/issues/184

**Comment by VasaXter** [comment]
Great job! thanks!
